### ISSUE TITLE
Reset playbook stuck on daemon-reload task

### ISSUE THREAD

**Issue by edenreich** [rancher/k3s-ansible#43]
When running reset playbook on a cluster of pi's it refuses to complete.

### Hardware
7x Pi 4 (8GB RAM)

### Software
* OS - Buster Lite (32bit)
* Ansible  2.9.9
* Python  2.7.17 

### Steps to reproduce

1) Run `ansible-playbook site.yml -i inventory/my-cluster/hosts.ini`
2) Run `ansible-playbook reset.yml -i inventory/my-cluster/hosts.ini`
3) Watch the tasks completing until it hits `TASK [reset : daemon_reload]` and get stuck forever (tried leaving it for at least half an hour) 

### Screenshot

![k3s-ansible](https://user-images.githubusercontent.com/16985712/84599913-d8354d80-ae75-11ea-9b16-0f26ec1a8c28.png)

### Configurations

`// inventory/my-cluster/group_vars/all.yml`
```yml
---
k3s_version: v1.17.5+k3s1
ansible_user: pi
systemd_dir: /etc/systemd/system
master_ip: "{{ hostvars[groups['master'][0]]['ansible_host'] | default(groups['master'][0]) }}"
extra_server_args: "--docker --no-deploy traefik"
```

`// inventory/my-cluster/hosts.ini`
```ini
[master]
192.168.1.xx

[node]
192.168.1.xx
192.168.1.xx
192.168.1.xx
192.168.1.xx
192.168.1.xx
192.168.1.xx

[k3s_cluster:children]
master
node
```

### Debug Information

```sh
ok: [192.168.1.xx] => {
    "changed": false, 
    "invocation": {
        "module_args": {
            "daemon_reexec": false, 
            "daemon_reload": true, 
            "enabled": null, 
            "force": null, 
            "masked": null, 
            "name": null, 
            "no_block": false, 
            "scope": null, 
            "state": null, 
            "user": null
        }
    }, 
    "name": null, 
    "status": {}
}
```

Sense it's the last task of that reset role, it is in fact deleting and cleaning the installation, however it still gets stuck without exiting.
