### ISSUE TITLE
Site playbook throws a syntax error on architecture check

### ISSUE THREAD

**Issue by edenreich** [rancher/k3s-ansible#44]
When running site playbook on a cluster of pi's it throws a syntax error.

### Hardware
7x Pi 4 (8GB RAM)

### Software
* OS - Buster Lite (32bit)
* Ansible  2.9.9
* Python  2.7.17 

### Steps to reproduce

1) Run `ansible-playbook site.yml -i inventory/my-cluster/hosts.ini`
3) Watch the tasks completing until ansible hits `TASK [raspbian : Activating cgroup support]` and throws a syntax error.

### Screenshot

![k3s-ansible-site](https://user-images.githubusercontent.com/16985712/84600478-b3db7000-ae79-11ea-9d32-5a25495dcdf2.png)

### Configurations

`// inventory/my-cluster/group_vars/all.yml`
```yml
---
k3s_version: v1.17.5+k3s1
ansible_user: pi
systemd_dir: /etc/systemd/system
master_ip: "{{ hostvars[groups['master'][0]]['ansible_host'] | default(groups['master'][0]) }}"
extra_server_args: "--docker --no-deploy traefik"
```

`// inventory/my-cluster/hosts.ini`
```ini
[master]
192.168.1.xx

[node]
192.168.1.xx
192.168.1.xx
192.168.1.xx
192.168.1.xx
192.168.1.xx
192.168.1.xx

[k3s_cluster:children]
master
node
```
