### ISSUE TITLE
 no action detected in task

### ISSUE THREAD

**Issue by shohidulhaque** [rancher/k3s-ansible#46]
when I run the following command with Ansible version ansible 2.5.1 on Ubuntu 18 LTS

ansible-playbook site.yml -i inventory/my-cluster/hosts.ini

The following error is produced:

ERROR! no action detected in task. This often indicates a misspelled module name, or incorrect module path.

The error appears to have been in '/home/thepoetwarrior/Downloads/k3s-ansible-master/roles/raspbian/tasks/main.yml': line 41, column 3, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

- name: Rebooting
  ^ here

My current config for this playbook is:

      file: inventory/my-cluster/hosts.ini 
[master]
192.168.0.50

[node]
192.168.0.51
192.168.0.52
192.168.0.53

[k3s_cluster:children]
master
node

    file:inventory/my-cluster/group_vars/all.yml 
---
k3s_version: v1.17.5+k3s1
ansible_user: pi
systemd_dir: /etc/systemd/system
master_ip: "{{ hostvars[groups['master'][0]]['ansible_host'] | default(groups['master'][0]) }}"
extra_server_args: ""

**Comment by shohidulhaque** [comment]
I used the wrong version of ansible.

**Comment by mkmojo** [comment]
I ran into this same issue when using an older version of ansible.
After doing the following I was able to update my ansible to a newer version, which fixes the issue:
```
$ sudo apt update
$ sudo apt install software-properties-common
$ sudo apt-add-repository --yes --update ppa:ansible/ansible
$ sudo apt install ansible
```

My old version is: 2.5.1
Working version is: 2.9.10

**Comment by mkmojo** [comment]
Hi @shohidulhaque,

After fixing this, were you able to see all your nodes showing up by:
```
kubectl get nodes
```

I can only find my master node in the cluster.

**Comment by shohidulhaque** [comment]
Hi,

I have version ansible 2.9.10 currently installed. Maybe I have updated my version not sure. The way I got the installation to work was by changing a file. use the cd command to go to the folder the project was cloned. Go to the folder roles/raspbian/tasks/ and change main.yml to:

```
 - name: Test for Raspbian
  set_fact:
    raspbian: true

- name: Activating cgroup support
  lineinfile:
    path: /boot/cmdline.txt
    regexp: '^((?!.*\bcgroup_enable=cpuset cgroup_memory=1 cgroup_enable=memory\b).*)$'
    line: '\1 cgroup_enable=cpuset cgroup_memory=1 cgroup_enable=memory'
    backrefs: true


- name: Flush iptables before changing to iptables-legacy
  iptables:
    flush: true


- name: Changing to iptables-legacy
  alternatives:
    path: /usr/sbin/iptables-legacy
    name: iptables
  register: ip4_legacy


- name: Changing to ip6tables-legacy
  alternatives:
    path: /usr/sbin/ip6tables-legacy
    name: ip6tables
  register: ip6_legacy


- name: Rebooting
  reboot:
```

I hope this helps.
