### ISSUE TITLE
validate k3s checksum on download roles

### ISSUE THREAD

**Issue by FinalDes** [rancher/k3s-ansible#67]
validate k3s checksum on download roles and shouldn't be deleted if checksum match when k3s already exists

**Comment by VeselaHouba** [comment]
There are more non-idempotent tasks in roles. I'll try to fix and send PR.

**Comment by FinalDes** [comment]
```
- name: Download k3s binary x64
  get_url:
    url: https://github.com/rancher/k3s/releases/download/{{ k3s_version }}/k3s
    dest: /usr/local/bin/k3s
    owner: root
    group: root
    mode: 0755
   checksum: ""
  when: ansible_facts.architecture == "x86_64"
```
just need to add checksum on get_url will solve idempotent on that task

I don't how to get checksum form the url: https://github.com/rancher/k3s/releases/download/{{ k3s_version }}/sha256sum-amd64.txt with follow content:
```
8382046072f6e8882e5d903deb5b64fa98663fb868e7ac0a62b611e227d2fb04  k3s
74d21a9731ae984772fd562403ac17db49b493e05592d69d5b21df85ab44c385  k3s-airgap-images-amd64.tar
53b68e92d10a346d4d75c52f784f4ccdc54f4395e0fc264027b79499143961af  k3s-images.txt
```
